sentry_control:
  ros__parameters:
    dt: 50
    have_bumpy_area: true
    deadband: 0.01
    path_topic: "plan"

    pid:
      kp: 5.0
      ki: 0.2
      kd: 0.4
      max_: 3.0
      min_: -3.0

    friend_bumpy_area:
      x_max: 3.3
      x_min: 1.0
      y_max: -6.0
      y_min: -8.0
    
    enermy_bumpy_area:
      x_max: 18.5
      x_min: 16.5
      y_max: 6.5
      y_min: 4.5

# 己方堡垒： x: 2.53, y:-0.54
# 敌方堡垒： x: 17.5, y:-5.5