path_checker:
  ros__parameters:
    path_topic: "plan"

    friend_bumpy_area:
      x_max: 3.3
      x_min: 1.0
      y_max: -6.0
      y_min: -8.0
    
    enermy_bumpy_area:
      x_max: 18.5
      x_min: 16.5
      y_max: 6.5
      y_min: 4.5
