image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2391.8999 ,    0.     ,  754.67044,
            0.     , 2383.10765,  532.77003,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.018808, 0.017769, 0.000373, 0.002575, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2387.59543,    0.     ,  756.45491,    0.     ,
            0.     , 2381.88892,  532.91686,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]